
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp:
        auth: false
        starttls.enable: false

