server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/fitness_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  mail:
    host: maildev
    port: 1025
    properties:
      mail.smtp:
        auth: false
        starttls.enable: false

application:
  base-url: http://auth:8081