version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 10s
      retries: 10
    networks:
      - fitness-network

  maildev:
    image: maildev/maildev:2.0.5
    ports:
      - "1080:1080"   # Web interface
      - "1025:1025"   # SMTP server
    networks:
      - fitness-network


volumes:
  mysql_data:

networks:
  fitness-network:
    driver: bridge