services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  maildev:
    image: maildev/maildev:2.0.5
    container_name: maildev
    ports:
      - "1080:1080"   # Web interface
      - "1025:1025"   # SMTP server

  eureka:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    depends_on:
      mysql:
        condition: service_healthy

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
      - eureka

  nutrition:
    build:
      context: ./nutrition-service
      dockerfile: Dockerfile
    container_name: nutrition
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka

  workout:
    build:
      context: ./workout-service
      dockerfile: Dockerfile
    container_name: workout
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka

  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - nutrition
      - workout
      - eureka

volumes:
  mysql_data: