spring:
  application:
    name: nutrition-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: fitness_user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

cors:
  allowed-origin: lb://api-gateway:8080
