server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/fitness_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true