server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Gateway, FitnessGateway

jwt:
  secret: QNP5EZNjpOBl++i0jpN06cmaoeCA+d3VMoFHiOns7G4=
