spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: nutrition-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/nutrition/**
        - id: exercise-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/exercise/**